# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - ldflags:
      - '-s'
      - '-w'
      - '-X "github.com/bilbilak/treegen/config.Version={{.Env.APP_VERSION}}"'
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - 386
      - arm
      - amd64
      - arm64
      - ppc64le
      - riscv64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - license: GPL-3.0
    vendor: Bilbilak
    maintainer: The Artifex (4r7if3x)
    homepage: https://github.com/bilbilak/treegen
    description: ASCII Tree Directory and File Structure Generator
    section: utils
    formats:
      - deb
      - rpm
      - archlinux
    contents:
      - src: treegen.1
        dst: /usr/local/share/man/man1/
